create table T_MENU(
   C_ID VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '主键(自增长)',
   C_REMARK VARCHAR(300) NULL COMMENT '备注',
   C_CREATE_USER VARCHAR(32) NOT NULL COMMENT '创建人',
   C_UPDATE_USER VARCHAR(32) NULL COMMENT '更新人',
   C_CREATE_TIME datetime COMMENT '创建时间',
   C_UPDATE_TIME datetime COMMENT '更新时间',
   C_DEL CHAR(1) NOT NULL COMMENT '删除标记 是否删除  Y是 N 否',
   C_VERSION VARCHAR(10)  NULL COMMENT '版本号',
   C_CODE VARCHAR(64) NOT NULL UNIQUE COMMENT '菜单编码',
   C_NAME VARCHAR(64) NOT NULL COMMENT '菜单名称',
   C_PARENT_CODE VARCHAR(64) NULL COMMENT '父级菜单',
   C_LEVEL INT NOT NULL COMMENT '菜单级别',
   C_URL VARCHAR(125) NULL COMMENT '菜单URL',
   C_ICON VARCHAR(32) NULL COMMENT '菜单ICON',
   C_SORT INT NULL COMMENT '排序',
   C_SPELL VARCHAR(32)  NULL COMMENT '拼音码'
)COMMENT = '菜单信息表';
	