create table T_DICT(
   C_ID VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '主键(编码)',
   C_CODE VARCHAR(64) NOT NULL UNIQUE COMMENT '字典编码',
   C_TYPE VARCHAR(32) NULL COMMENT '类型',
   C_DEFAULT CHAR(1) NULL COMMENT '是否默认 Y/N',
   C_NAME VARCHAR(64) NULL COMMENT '名称',
   C_TAG VARCHAR(255) NULL COMMENT '标记',
   C_REMARK VARCHAR(300) NULL COMMENT '备注',
   C_CREATE_USER VARCHAR(32) NOT NULL COMMENT '创建人',
   C_UPDATE_USER VARCHAR(32) NULL COMMENT '更新人',
   C_CREATE_TIME datetime COMMENT '创建时间',
   C_UPDATE_TIME datetime COMMENT '更新时间',
   C_DEL CHAR(1) NOT NULL COMMENT '删除标记 是否删除  Y是 N 否',
   C_VERSION BIGINT  NULL COMMENT '版本号',
   C_SORT INT NULL COMMENT '排序',
   C_SPELL VARCHAR(16) NULL COMMENT '拼音码'
)COMMENT = '字典信息表';
