create table T_DICT(
   C_ID VARCHAR(100) NOT NULL PRIMARY KEY COMMENT '主键(编码)',
   C_CODE VARCHAR(64) NOT NULL UNIQUE COMMENT '客户编码',
   C_CATEGORY VARCHAR(32) NULL COMMENT '客户类别，字典码',
   C_STATUS VARCHAR(32) NULL COMMENT '客户状态，枚举字典',
   C_ORIGIN VARCHAR(32) NULL COMMENT '客户来源，枚举字典',
   C_ISVIP CHAR(1) NULL COMMENT '是否VIP,Y/N',
   C_ISINPOOL CHAR(1) NULL COMMENT '是否掉公,Y/N',
   C_ISIMPORT CHAR(1) NULL COMMENT '是否导入客,Y/N',
   C_REMARK VARCHAR(300) NULL COMMENT '备注',
   C_CREATE_USER VARCHAR(32) NOT NULL COMMENT '创建人',
   C_UPDATE_USER VARCHAR(32) NULL COMMENT '更新人',
   C_CREATE_TIME datetime COMMENT '创建时间',
   C_UPDATE_TIME datetime COMMENT '更新时间',
   C_DEL CHAR(1) NOT NULL COMMENT '删除标记 是否删除  Y是 N 否',
   C_VERSION BIGINT  NULL COMMENT '版本号',
   C_SORT INT NULL COMMENT '排序'
)COMMENT = '客户信息表';
